/* 
Data adapted from 
https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes

What is a country, and what is a capital, can vary depending on who you ask. 
The World Bank doesn't list a capital city for some of the countries in the list 
linked to above, so those have been removed from the array of data. 
*/

let countriesAndCodes = [
    {'name':'Afghanistan', 'twoLetterCode':'AF', 'numericCode':'004'},
    {'name':'Albania', 'twoLetterCode':'AL', 'numericCode':'008'},
    {'name':'Algeria', 'twoLetterCode':'DZ', 'numericCode':'012'},
    {'name':'American Samoa', 'twoLetterCode':'AS', 'numericCode':'016'},
    {'name':'Andorra', 'twoLetterCode':'AD', 'numericCode':'020'},
    {'name':'Angola', 'twoLetterCode':'AO', 'numericCode':'024'},
    {'name':'Antigua and Barbuda', 'twoLetterCode':'AG', 'numericCode':'028'},
    {'name':'Argentina', 'twoLetterCode':'AR', 'numericCode':'032'},
    {'name':'Armenia', 'twoLetterCode':'AM', 'numericCode':'051'},
    {'name':'Aruba', 'twoLetterCode':'AW', 'numericCode':'533'},
    {'name':'Australia', 'twoLetterCode':'AU', 'numericCode':'036'},
    {'name':'Austria', 'twoLetterCode':'AT', 'numericCode':'040'},
    {'name':'Azerbaijan', 'twoLetterCode':'AZ', 'numericCode':'031'},
    {'name':'Bahamas', 'twoLetterCode':'BS', 'numericCode':'044'},
    {'name':'Bahrain', 'twoLetterCode':'BH', 'numericCode':'048'},
    {'name':'Bangladesh', 'twoLetterCode':'BD', 'numericCode':'050'},
    {'name':'Barbados', 'twoLetterCode':'BB', 'numericCode':'052'},
    {'name':'Belarus', 'twoLetterCode':'BY', 'numericCode':'112'},
    {'name':'Belgium', 'twoLetterCode':'BE', 'numericCode':'056'},
    {'name':'Belize', 'twoLetterCode':'BZ', 'numericCode':'084'},
    {'name':'Benin', 'twoLetterCode':'BJ', 'numericCode':'204'},
    {'name':'Bermuda', 'twoLetterCode':'BM', 'numericCode':'060'},
    {'name':'Bhutan', 'twoLetterCode':'BT', 'numericCode':'064'},
    {'name':'Bolivia (Plurinational State of)', 'twoLetterCode':'BO', 'numericCode':'068'},
    {'name':'Bosnia and Herzegovina', 'twoLetterCode':'BA', 'numericCode':'070'},
    {'name':'Botswana', 'twoLetterCode':'BW', 'numericCode':'072'},
    {'name':'Brazil', 'twoLetterCode':'BR', 'numericCode':'076'},
    {'name':'Brunei Darussalam', 'twoLetterCode':'BN', 'numericCode':'096'},
    {'name':'Bulgaria', 'twoLetterCode':'BG', 'numericCode':'100'},
    {'name':'Burkina Faso', 'twoLetterCode':'BF', 'numericCode':'854'},
    {'name':'Burundi', 'twoLetterCode':'BI', 'numericCode':'108'},
    {'name':'Cabo Verde', 'twoLetterCode':'CV', 'numericCode':'132'},
    {'name':'Cambodia', 'twoLetterCode':'KH', 'numericCode':'116'},
    {'name':'Cameroon', 'twoLetterCode':'CM', 'numericCode':'120'},
    {'name':'Canada', 'twoLetterCode':'CA', 'numericCode':'124'},
    {'name':'Cayman Islands', 'twoLetterCode':'KY', 'numericCode':'136'},
    {'name':'Central African Republic', 'twoLetterCode':'CF', 'numericCode':'140'},
    {'name':'Chad', 'twoLetterCode':'TD', 'numericCode':'148'},
    {'name':'Chile', 'twoLetterCode':'CL', 'numericCode':'152'},
    {'name':'China', 'twoLetterCode':'CN', 'numericCode':'156'},
    {'name':'Colombia', 'twoLetterCode':'CO', 'numericCode':'170'},
    {'name':'Comoros', 'twoLetterCode':'KM', 'numericCode':'174'},
    {'name':'Congo', 'twoLetterCode':'CG', 'numericCode':'178'},
    {'name':'Congo (Democratic Republic of the)', 'twoLetterCode':'CD', 'numericCode':'180'},
    {'name':'Costa Rica', 'twoLetterCode':'CR', 'numericCode':'188'},
    {'name':'Côte d\'Ivoire', 'twoLetterCode':'CI', 'numericCode':'384'},
    {'name':'Croatia', 'twoLetterCode':'HR', 'numericCode':'191'},
    {'name':'Cuba', 'twoLetterCode':'CU', 'numericCode':'192'},
    {'name':'Curaçao', 'twoLetterCode':'CW', 'numericCode':'531'},
    {'name':'Cyprus', 'twoLetterCode':'CY', 'numericCode':'196'},
    {'name':'Czechia', 'twoLetterCode':'CZ', 'numericCode':'203'},
    {'name':'Denmark', 'twoLetterCode':'DK', 'numericCode':'208'},
    {'name':'Djibouti', 'twoLetterCode':'DJ', 'numericCode':'262'},
    {'name':'Dominica', 'twoLetterCode':'DM', 'numericCode':'212'},
    {'name':'Dominican Republic', 'twoLetterCode':'DO', 'numericCode':'214'},
    {'name':'Ecuador', 'twoLetterCode':'EC', 'numericCode':'218'},
    {'name':'Egypt', 'twoLetterCode':'EG', 'numericCode':'818'},
    {'name':'El Salvador', 'twoLetterCode':'SV', 'numericCode':'222'},
    {'name':'Equatorial Guinea', 'twoLetterCode':'GQ', 'numericCode':'226'},
    {'name':'Eritrea', 'twoLetterCode':'ER', 'numericCode':'232'},
    {'name':'Estonia', 'twoLetterCode':'EE', 'numericCode':'233'},
    {'name':'Eswatini', 'twoLetterCode':'SZ', 'numericCode':'748'},
    {'name':'Ethiopia', 'twoLetterCode':'ET', 'numericCode':'231'},
    {'name':'Faroe Islands', 'twoLetterCode':'FO', 'numericCode':'234'},
    {'name':'Fiji', 'twoLetterCode':'FJ', 'numericCode':'242'},
    {'name':'Finland', 'twoLetterCode':'FI', 'numericCode':'246'},
    {'name':'France', 'twoLetterCode':'FR', 'numericCode':'250'},
    {'name':'French Polynesia', 'twoLetterCode':'PF', 'numericCode':'258'},
    {'name':'Gabon', 'twoLetterCode':'GA', 'numericCode':'266'},
    {'name':'Gambia', 'twoLetterCode':'GM', 'numericCode':'270'},
    {'name':'Georgia', 'twoLetterCode':'GE', 'numericCode':'268'},
    {'name':'Germany', 'twoLetterCode':'DE', 'numericCode':'276'},
    {'name':'Ghana', 'twoLetterCode':'GH', 'numericCode':'288'},
    {'name':'Greece', 'twoLetterCode':'GR', 'numericCode':'300'},
    {'name':'Greenland', 'twoLetterCode':'GL', 'numericCode':'304'},
    {'name':'Grenada', 'twoLetterCode':'GD', 'numericCode':'308'},
    {'name':'Guam', 'twoLetterCode':'GU', 'numericCode':'316'},
    {'name':'Guatemala', 'twoLetterCode':'GT', 'numericCode':'320'},
    {'name':'Guinea', 'twoLetterCode':'GN', 'numericCode':'324'},
    {'name':'Guinea-Bissau', 'twoLetterCode':'GW', 'numericCode':'624'},
    {'name':'Guyana', 'twoLetterCode':'GY', 'numericCode':'328'},
    {'name':'Haiti', 'twoLetterCode':'HT', 'numericCode':'332'},
    {'name':'Honduras', 'twoLetterCode':'HN', 'numericCode':'340'},
    {'name':'Hungary', 'twoLetterCode':'HU', 'numericCode':'348'},
    {'name':'Iceland', 'twoLetterCode':'IS', 'numericCode':'352'},
    {'name':'India', 'twoLetterCode':'IN', 'numericCode':'356'},
    {'name':'Indonesia', 'twoLetterCode':'ID', 'numericCode':'360'},
    {'name':'Iran (Islamic Republic of)', 'twoLetterCode':'IR', 'numericCode':'364'},
    {'name':'Iraq', 'twoLetterCode':'IQ', 'numericCode':'368'},
    {'name':'Ireland', 'twoLetterCode':'IE', 'numericCode':'372'},
    {'name':'Isle of Man', 'twoLetterCode':'IM', 'numericCode':'833'},
    {'name':'Italy', 'twoLetterCode':'IT', 'numericCode':'380'},
    {'name':'Jamaica', 'twoLetterCode':'JM', 'numericCode':'388'},
    {'name':'Japan', 'twoLetterCode':'JP', 'numericCode':'392'},
    {'name':'Jordan', 'twoLetterCode':'JO', 'numericCode':'400'},
    {'name':'Kazakhstan', 'twoLetterCode':'KZ', 'numericCode':'398'},
    {'name':'Kenya', 'twoLetterCode':'KE', 'numericCode':'404'},
    {'name':'Kiribati', 'twoLetterCode':'KI', 'numericCode':'296'},
    {'name':'Korea (Democratic People\'s Republic of)', 'twoLetterCode':'KP', 'numericCode':'408'},
    {'name':'Korea (Republic of)', 'twoLetterCode':'KR', 'numericCode':'410'},
    {'name':'Kuwait', 'twoLetterCode':'KW', 'numericCode':'414'},
    {'name':'Kyrgyzstan', 'twoLetterCode':'KG', 'numericCode':'417'},
    {'name':'Lao People\'s Democratic Republic', 'twoLetterCode':'LA', 'numericCode':'418'},
    {'name':'Latvia', 'twoLetterCode':'LV', 'numericCode':'428'},
    {'name':'Lebanon', 'twoLetterCode':'LB', 'numericCode':'422'},
    {'name':'Lesotho', 'twoLetterCode':'LS', 'numericCode':'426'},
    {'name':'Liberia', 'twoLetterCode':'LR', 'numericCode':'430'},
    {'name':'Libya', 'twoLetterCode':'LY', 'numericCode':'434'},
    {'name':'Liechtenstein', 'twoLetterCode':'LI', 'numericCode':'438'},
    {'name':'Lithuania', 'twoLetterCode':'LT', 'numericCode':'440'},
    {'name':'Luxembourg', 'twoLetterCode':'LU', 'numericCode':'442'},
    {'name':'Macedonia (the former Yugoslav Republic of)', 'twoLetterCode':'MK', 'numericCode':'807'},
    {'name':'Madagascar', 'twoLetterCode':'MG', 'numericCode':'450'},
    {'name':'Malawi', 'twoLetterCode':'MW', 'numericCode':'454'},
    {'name':'Malaysia', 'twoLetterCode':'MY', 'numericCode':'458'},
    {'name':'Maldives', 'twoLetterCode':'MV', 'numericCode':'462'},
    {'name':'Mali', 'twoLetterCode':'ML', 'numericCode':'466'},
    {'name':'Malta', 'twoLetterCode':'MT', 'numericCode':'470'},
    {'name':'Marshall Islands', 'twoLetterCode':'MH', 'numericCode':'584'},
    {'name':'Mauritania', 'twoLetterCode':'MR', 'numericCode':'478'},
    {'name':'Mauritius', 'twoLetterCode':'MU', 'numericCode':'480'},
    {'name':'Mexico', 'twoLetterCode':'MX', 'numericCode':'484'},
    {'name':'Micronesia (Federated States of)', 'twoLetterCode':'FM', 'numericCode':'583'},
    {'name':'Moldova (Republic of)', 'twoLetterCode':'MD', 'numericCode':'498'},
    {'name':'Monaco', 'twoLetterCode':'MC', 'numericCode':'492'},
    {'name':'Mongolia', 'twoLetterCode':'MN', 'numericCode':'496'},
    {'name':'Montenegro', 'twoLetterCode':'ME', 'numericCode':'499'},
    {'name':'Morocco', 'twoLetterCode':'MA', 'numericCode':'504'},
    {'name':'Mozambique', 'twoLetterCode':'MZ', 'numericCode':'508'},
    {'name':'Myanmar', 'twoLetterCode':'MM', 'numericCode':'104'},
    {'name':'Namibia', 'twoLetterCode':'NA', 'numericCode':'516'},
    {'name':'Nauru', 'twoLetterCode':'NR', 'numericCode':'520'},
    {'name':'Nepal', 'twoLetterCode':'NP', 'numericCode':'524'},
    {'name':'Netherlands', 'twoLetterCode':'NL', 'numericCode':'528'},
    {'name':'New Caledonia', 'twoLetterCode':'NC', 'numericCode':'540'},
    {'name':'New Zealand', 'twoLetterCode':'NZ', 'numericCode':'554'},
    {'name':'Nicaragua', 'twoLetterCode':'NI', 'numericCode':'558'},
    {'name':'Niger', 'twoLetterCode':'NE', 'numericCode':'562'},
    {'name':'Nigeria', 'twoLetterCode':'NG', 'numericCode':'566'},
    {'name':'Northern Mariana Islands', 'twoLetterCode':'MP', 'numericCode':'580'},
    {'name':'Norway', 'twoLetterCode':'NO', 'numericCode':'578'},
    {'name':'Oman', 'twoLetterCode':'OM', 'numericCode':'512'},
    {'name':'Pakistan', 'twoLetterCode':'PK', 'numericCode':'586'},
    {'name':'Palau', 'twoLetterCode':'PW', 'numericCode':'585'},
    {'name':'Panama', 'twoLetterCode':'PA', 'numericCode':'591'},
    {'name':'Papua New Guinea', 'twoLetterCode':'PG', 'numericCode':'598'},
    {'name':'Paraguay', 'twoLetterCode':'PY', 'numericCode':'600'},
    {'name':'Peru', 'twoLetterCode':'PE', 'numericCode':'604'},
    {'name':'Philippines', 'twoLetterCode':'PH', 'numericCode':'608'},
    {'name':'Poland', 'twoLetterCode':'PL', 'numericCode':'616'},
    {'name':'Portugal', 'twoLetterCode':'PT', 'numericCode':'620'},
    {'name':'Puerto Rico', 'twoLetterCode':'PR', 'numericCode':'630'},
    {'name':'Qatar', 'twoLetterCode':'QA', 'numericCode':'634'},
    {'name':'Romania', 'twoLetterCode':'RO', 'numericCode':'642'},
    {'name':'Russian Federation', 'twoLetterCode':'RU', 'numericCode':'643'},
    {'name':'Rwanda', 'twoLetterCode':'RW', 'numericCode':'646'},
    {'name':'Saint Kitts and Nevis', 'twoLetterCode':'KN', 'numericCode':'659'},
    {'name':'Saint Lucia', 'twoLetterCode':'LC', 'numericCode':'662'},
    {'name':'Saint Martin (French part)', 'twoLetterCode':'MF', 'numericCode':'663'},
    {'name':'Saint Vincent and the Grenadines', 'twoLetterCode':'VC', 'numericCode':'670'},
    {'name':'Samoa', 'twoLetterCode':'WS', 'numericCode':'882'},
    {'name':'San Marino', 'twoLetterCode':'SM', 'numericCode':'674'},
    {'name':'Sao Tome and Principe', 'twoLetterCode':'ST', 'numericCode':'678'},
    {'name':'Saudi Arabia', 'twoLetterCode':'SA', 'numericCode':'682'},
    {'name':'Senegal', 'twoLetterCode':'SN', 'numericCode':'686'},
    {'name':'Serbia', 'twoLetterCode':'RS', 'numericCode':'688'},
    {'name':'Seychelles', 'twoLetterCode':'SC', 'numericCode':'690'},
    {'name':'Sierra Leone', 'twoLetterCode':'SL', 'numericCode':'694'},
    {'name':'Singapore', 'twoLetterCode':'SG', 'numericCode':'702'},
    {'name':'Sint Maarten (Dutch part)', 'twoLetterCode':'SX', 'numericCode':'534'},
    {'name':'Slovakia', 'twoLetterCode':'SK', 'numericCode':'703'},
    {'name':'Slovenia', 'twoLetterCode':'SI', 'numericCode':'705'},
    {'name':'Solomon Islands', 'twoLetterCode':'SB', 'numericCode':'090'},
    {'name':'Somalia', 'twoLetterCode':'SO', 'numericCode':'706'},
    {'name':'South Africa', 'twoLetterCode':'ZA', 'numericCode':'710'},
    {'name':'South Sudan', 'twoLetterCode':'SS', 'numericCode':'728'},
    {'name':'Spain', 'twoLetterCode':'ES', 'numericCode':'724'},
    {'name':'Sri Lanka', 'twoLetterCode':'LK', 'numericCode':'144'},
    {'name':'Sudan', 'twoLetterCode':'SD', 'numericCode':'729'},
    {'name':'Suriname', 'twoLetterCode':'SR', 'numericCode':'740'},
    {'name':'Sweden', 'twoLetterCode':'SE', 'numericCode':'752'},
    {'name':'Switzerland', 'twoLetterCode':'CH', 'numericCode':'756'},
    {'name':'Syrian Arab Republic', 'twoLetterCode':'SY', 'numericCode':'760'},
    {'name':'Tajikistan', 'twoLetterCode':'TJ', 'numericCode':'762'},
    {'name':'Tanzania, United Republic of', 'twoLetterCode':'TZ', 'numericCode':'834'},
    {'name':'Thailand', 'twoLetterCode':'TH', 'numericCode':'764'},
    {'name':'Timor-Leste', 'twoLetterCode':'TL', 'numericCode':'626'},
    {'name':'Togo', 'twoLetterCode':'TG', 'numericCode':'768'},
    {'name':'Tonga', 'twoLetterCode':'TO', 'numericCode':'776'},
    {'name':'Trinidad and Tobago', 'twoLetterCode':'TT', 'numericCode':'780'},
    {'name':'Tunisia', 'twoLetterCode':'TN', 'numericCode':'788'},
    {'name':'Turkey', 'twoLetterCode':'TR', 'numericCode':'792'},
    {'name':'Turkmenistan', 'twoLetterCode':'TM', 'numericCode':'795'},
    {'name':'Turks and Caicos Islands', 'twoLetterCode':'TC', 'numericCode':'796'},
    {'name':'Tuvalu', 'twoLetterCode':'TV', 'numericCode':'798'},
    {'name':'Uganda', 'twoLetterCode':'UG', 'numericCode':'800'},
    {'name':'Ukraine', 'twoLetterCode':'UA', 'numericCode':'804'},
    {'name':'United Arab Emirates', 'twoLetterCode':'AE', 'numericCode':'784'},
    {'name':'United Kingdom of Great Britain and Northern Ireland', 'twoLetterCode':'GB', 'numericCode':'826'},
    {'name':'United States of America', 'twoLetterCode':'US', 'numericCode':'840'},
    {'name':'Uruguay', 'twoLetterCode':'UY', 'numericCode':'858'},
    {'name':'Uzbekistan', 'twoLetterCode':'UZ', 'numericCode':'860'},
    {'name':'Vanuatu', 'twoLetterCode':'VU', 'numericCode':'548'},
    {'name':'Venezuela (Bolivarian Republic of)', 'twoLetterCode':'VE', 'numericCode':'862'},
    {'name':'Viet Nam', 'twoLetterCode':'VN', 'numericCode':'704'},
    {'name':'Virgin Islands (British)', 'twoLetterCode':'VG', 'numericCode':'092'},
    {'name':'Virgin Islands (U.S.)', 'twoLetterCode':'VI', 'numericCode':'850'},
    {'name':'Yemen', 'twoLetterCode':'YE', 'numericCode':'887'},
    {'name':'Zambia', 'twoLetterCode':'ZM', 'numericCode':'894'},
    {'name':'Zimbabwe', 'twoLetterCode':'ZW', 'numericCode':'716'}
]